FindTutors/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
from SuperTuber import settings
from django.conf.urls.static import static

app_name = 'FindTutors'

urlpatterns = [
    path('register/', views.SignUpView.as_view(), name='signup'),
    path('tutors/', views.Tutors, name='tutors'),
    path('tutees/', views.Tutees, name='tutees'),
    path('request/', views.RequestView.as_view(), name='request'),
    path('register_tutor/', views.TutorRegister.as_view(), name='tutor_register'),
    path('register_tutee/', views.TuteeRegisterView.as_view(), name='tutee_register'),
    path('request/tutor_request/', views.TutorRequest, name='tutor_request'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit', views.editprofile, name='edit_profile'),
    path('request/tutor_request/', views.TutorRequest, name='tutor_request'),
    path('tutors/<pk>/', views.TutorProfile, name='tutor_profile'),
    path('ratingsreview/', views.ReviewRating, name='ratings_review'),
    url(r'messages/$', views.all_rooms, name="all_rooms"),
    url(r'token$', views.token, name="token"),
    url(r'(?P<slug>[-\w]+)/$', views.room_detail, name="room_detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SuperTuber/urls.py
from django.contrib import admin
from django.urls import path
from FindTutors import views
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('home/', include('FindTutors.urls')),
    path('admin/', admin.site.urls),
    path('home/', views.HomeView.as_view(), name='home'),
    path('', views.SignUpView.as_view(), name='signup'),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('complete/google-oauth2/home/',views.redirectView.as_view(), name='redirect'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FindTutors/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, UserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from PIL import Image


class UserManager(BaseUserManager):

    def _create_user(self, username, email, password, is_staff, is_superuser):
        if not email:
            raise ValueError('user must have email address')
        email = self.normalize_email(email)
        user = self.model(username=username,
                          email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser,
                          )
        # We check if password has been given
        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user


# We change following functions signature to allow "No password"

    def create_user(self, username, email, password=None):
        return self._create_user(username, email, password, False, False)

    def create_superuser(self, username, email, password=None):
        user = self._create_user(username, email, password, True, True)
        user.save(using=self._db)
        return user


class TUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=200, default='')
    email = models.EmailField(('email address'), unique=True)
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    image = models.ImageField(
        default='tutor_profile/default.png', upload_to='tutor_profile')
    phone_number = models.IntegerField(blank=True, null=True)
    is_tutee = models.BooleanField('student status', default=False)
    is_tutor = models.BooleanField('teacher status', default=False)
    year = models.IntegerField(blank=True, null=True)
    SUBJECT_CHOICES = (
        ('Computer Science', 'Computer Science'),
        ('Biology', 'Biology'),
        ('Chemistry', 'Chemistry'),
        ('Physics', 'Physics'),
        ('Math', 'Math'),
        ('English', 'English'),
        ('Algebra', 'Algebra'),
        ('Calculus', 'Calculus'),
        ('Geometry', 'Geometry'),
        ('Language', 'Language'),
        ('Reading', 'Reading'),
        ('Music', 'Music'),
    )
    subjects = models.CharField(max_length=30, choices=SUBJECT_CHOICES)
    bio = models.TextField(default=' ')
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


# profile of tutee?
class Profile(models.Model):
    user = models.OneToOneField(TUser, on_delete=models.CASCADE)
    # firstname = TUser.firstname
    # lastname = TUser.lastname
    firstname = models.CharField(max_length=100, default=' ')
    lastname = models.CharField(max_length=100, default=' ')
    image = models.ImageField(default='profile_pictures/default.jpg',
                              upload_to='profile_pictures')

    FIRST = '1st'
    SECOND = '2nd'
    THIRD = '3rd'
    FOURTH = '4th'
    YEAR_CHOICES = (
        (FIRST, 'First Year'),
        (SECOND, 'Second Year'),
        (THIRD, 'Third Year'),
        (FOURTH, 'Fourth Year'),
    )
    year = models.CharField(max_length=3, choices=YEAR_CHOICES, default=FIRST)

    TUTOR = 'tutor'
    TUTEE = 'tutee'
    BOTH = 'tutor_tutee'
    USER_CHOICES = (
        (FIRST, 'Tutor'),
        (SECOND, 'Tutee'),
        (THIRD, 'Tutor and Tutee'),
    )
    user_type = models.CharField(
        max_length=15, choices=USER_CHOICES, default=TUTOR)
    subjects = models.CharField(max_length=500, default="")
    bio = models.TextField(default=' ')

    def __str__(self):
        return "%s's profile" % self.user

    def save(self, *args, **kwargs):
        super().save()

        # img = Image.open(self.image.path)
        #
        # if img.height > 300 or img.width > 300:
        #     output_size = (300, 300)
        #     img.thumbnail(output_size)
        #     img.save(self.image.path)


class Reviews(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    # This would be what a tutee would rate a tutor?
    Zero = '0'
    One = '1'
    Two = '2'
    Three = '3'
    Four = '4'
    Five = '5'
    YEAR_CHOICES = (
        (Zero, "No Rating"),
        (One, 'One Star'),
        (Two, 'Two Stars'),
        (Three, 'Three Stars'),
        (Four, 'Four Stars'),
        (Five, 'Five Stars'),
    )
    rating = models.CharField(max_length=3, choices=YEAR_CHOICES, default=Zero)

    # This would be what a tutee would rate a tutor?
    reviews = models.TextField(default=' ')

# profile signal
@receiver(post_save, sender=TUser)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Request(models.Model):
    sender = models.ForeignKey(
        TUser, models.SET_NULL, related_name="TUser_sender", blank=True, null=True)
    recipient = models.ForeignKey(
        TUser, models.SET_NULL, related_name="TUser_recipient", blank=True, null=True)
    subject = models.CharField(max_length=500, default="",)
    description = models.CharField(max_length=500, default="")
    location = models.CharField(max_length=500, default="")

# https://www.twilio.com/blog/2018/05/build-chat-python-django-applications-programmable-chat.html


class Room(models.Model):
    """Represents chat rooms that users can join"""
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    slug = models.CharField(max_length=50)

    def __str__(self):
        """Returns human-readable representation of the model instance."""
        return self.name

FindTutors/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import TUser, Profile, Request, Reviews
from django.forms import ModelForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms import bootstrap
from django.utils.translation import gettext_lazy as _
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from crispy_forms.helper import FormHelper

SUBJECT_CHOICES = (
    ('Computer Science', 'Computer Science'),
    ('Biology', 'Biology'),
    ('Chemistry', 'Chemistry'),
    ('Physics', 'Physics'),
    ('Math', 'Math'),
    ('English', 'English'),
    ('Algebra', 'Algebra'),
    ('Calculus', 'Calculus'),
    ('Geometry', 'Geometry'),
    ('Language', 'Language'),
    ('Reading', 'Reading'),
    ('Music', 'Music'),
)


class RequestForm(ModelForm):
    class Meta:
        model = Request
        fields = ('subject', 'description', 'location',)


class RegisterForm(UserCreationForm):
    class Meta:
        model = TUser
        fields = ('firstname', 'lastname', 'email', 'phone_number',)


class TutorUserSignUpForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TutorUserSignUpForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        profile = Profile.objects.get(pk=self.user.pk)
        # self.initial['firstname'] = profile.user_type

    class Meta:
        model = TUser  # change model to TutorProfile and add bio
        fields = ['username', 'firstname', 'lastname',
                  'email', 'phone_number', 'subjects', 'image']
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'firstname': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'lastname': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'phone_number': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'subjects': forms.Select(
                choices=SUBJECT_CHOICES,
                attrs={
                    'class': 'form-control'
                }
            ),
            'image': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class TuteeUserSignUpForm(UserCreationForm):
    class Meta:
        model = TUser
        fields = ('firstname', 'lastname', 'email',
                  'phone_number', 'year', 'subjects')


# TutorRegistrationForm
class TutorRegistration(UserCreationForm):
    class Meta:
        model = TUser
        fields = ('firstname', 'lastname', 'phone_number', 'subjects')


# update user profile
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'year', 'user_type', 'subjects', 'bio']


class ReviewRatingForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['profile', 'rating', 'reviews']

FindTutors/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import login, logout, authenticate
from .models import Request, TUser, Reviews, Room, Profile
from .forms import RequestForm, RegisterForm, ProfileUpdateForm, TutorRegistration, TutorUserSignUpForm, \
    ReviewRatingForm
from django.views.generic import CreateView, ListView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import JsonResponse
from faker import Faker
from twilio.jwt.access_token import AccessToken
from twilio.jwt.access_token.grants import ChatGrant

# tutor register form view


class TutorRegister(CreateView):
    model = TUser
    form_class = TutorUserSignUpForm
    template_name = 'FindTutors/tutor_signup.html'  # correct form HTML

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_tutor = True
        user.save()
        return redirect('/home/tutors/')  # Go back to the table of tutors

    def get_form_kwargs(self):
        kwargs = super(TutorRegister, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    # def get(self, request, *args, **kwargs):
    #     self.object = None
    #     current_user = request.user
    #     entry = get_object_or_404(Profile, pk=current_user.id)
    #     context_data = self.get_context_data()
    #     context_data.update(entry=entry)
    #     return self.render_to_response(context_data)


class TuteeRegisterView(CreateView):
    model = TUser
    # form_class = RegisterForm               # check form
    fields = ['firstname', 'lastname', 'email', 'subjects', 'year', ]
    template_name = 'FindTutors/tutee_signup.html'  # correct form HTML

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_tutee = True
        user.save()
        return redirect('/home/tutees/')  # Go back to the table of tutors
        login(self.request, user)

        return redirect('dashboard')           # redirect to proper dashboard


def Tutors(request):
    model = TUser
    the_tutors = TUser.objects.filter(is_tutor=1)
    return render(request, 'FindTutors/tutors.html', {'tutors': the_tutors})


def TutorProfile(request, pk):
    if request.method == 'GET':
        profile = get_object_or_404(TUser, pk=pk)  # change to TutorProfile
        profile_id = pk
        reviews = Reviews.objects.filter(profile_id=profile_id)

        return render(request, 'FindTutors/tutor_profile.html', {'profile': profile, "reviews": reviews})


def Tutees(request):
    all_tutees = TUser.objects.filter(is_tutee=True)
    return render(request, 'FindTutors/tutees.html', {'tutees': all_tutees})

# registration views


class SignUpView(generic.TemplateView):
    template_name = 'registration/signup.html'


class redirectView(generic.TemplateView):
    template_name = 'registration/redirect.html'


class HomeView(generic.TemplateView):
    template_name = 'FindTutors/home.html'


class RequestView(generic.CreateView):
    model = Request
    form_class = RequestForm
    template_name = 'FindTutors/request.html'

    def form_valid(self, form):
        self.request_input = form.save(commit=False)
        self.request_input.sender = self.request.user
        self.request_input.recipient = TUser.objects.get(
            email=self.request.GET.get('recipient'))
        self.request_input.save()
        return redirect('/home/request/tutor_request/')


def TutorRequest(request):
    model = TUser
    all_tutors = TUser.objects.filter(is_tutor=True)
    if request.user.is_authenticated:
        print('user authenticated')
    return render(request, 'FindTutors/tutor_request.html', {'tutors': all_tutors})


class ProfileView(generic.TemplateView):
    template_name = 'FindTutors/myprofile.html'


@login_required
def editprofile(request):
    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST, request.FILES)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if p_form.is_valid():
            p_form.save()
            return redirect('FindTutors:profile')
    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'p_form': p_form
    }

    return render(request, 'FindTutors/editprofile.html', context)


def ReviewRating(request):
    if request.method == "POST":
        form = ReviewRatingForm(request.POST)
        if form.is_valid():
            rating = form.save()
            return redirect('/home/tutors/%s' % rating.profile_id)
    else:
        form = ReviewRatingForm()
    return render(request, 'FindTutors/ratings_review.html', {'form': form})


def all_rooms(request):
    rooms = Room.objects.all()
    return render(request, 'FindTutors/all_rooms.html', {'rooms': rooms})


def room_detail(request, slug):
    room = Room.objects.get(slug=slug)
    return render(request, 'FindTutors/room_detail.html', {'room': room})


fake = Faker()


def token(request):
    identity = request.GET.get('identity', fake.user_name())
    device_id = request.GET.get('device', 'default')  # unique device ID

    account_sid = settings.TWILIO_ACCOUNT_SID
    api_key = settings.TWILIO_API_KEY
    api_secret = settings.TWILIO_API_SECRET
    chat_service_sid = settings.TWILIO_CHAT_SERVICE_SID

    token = AccessToken(account_sid, api_key, api_secret, identity=identity)

    # Create a unique endpoint ID for the device
    endpoint = "MyDjangoChatRoom:{0}:{1}".format(identity, device_id)

    if chat_service_sid:
        chat_grant = ChatGrant(endpoint_id=endpoint,
                               service_sid=chat_service_sid)
        token.add_grant(chat_grant)

    response = {
        'identity': identity,
        'token': token.to_jwt().decode('utf-8')
    }

    return JsonResponse(response)

FindTutors/templates/FindTutors/all_rooms.html
{% extends 'FindTutors/base.html' %}
{% block content %}
{% for room in rooms %}
<div class="column">
  <div class="card rounded-edges">
    <div class="card-content">
      <p class="title is-4">{{room.name}}</p>
      <div class="content">
        <p>
          {{room.description}}
        </p>
        <a href="{{room.slug}}" class="button">Join Room</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

FindTutors/templates/FindTutors/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Home</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/css/mdb.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'FindTutors/style.css' %}" />
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">Super Tuber</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
          <li class="nav-item"><a  class="nav-link" href="{% url 'FindTutors:profile' %}">My Profile</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'FindTutors:tutors' %}">Find Tutors</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'FindTutors:all_rooms' %}">Messages</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'FindTutors:tutor_register' %}">Register as a Tutor</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log out</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <!-- JQuery -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js">
  </script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"></script>
</body>

</html>

FindTutors/templates/FindTutors/editprofile.html
{% extends 'FindTutors/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
    </div>
{% endblock content %}

FindTutors/templates/FindTutors/home.html
{% extends 'FindTutors/base.html' %}
{% block content %}
  <div class="col-lg-12 p-4 p-md-5 mb-4 mt-5 text-white rounded bg-dark supertuber-header">
   <div class="col-md-6 px-0 mx-auto">
      <h1 class="display-4  text-center text-light">Supertuber</h1>
      <p class="lead text-center text-light">Quickly Find Help For Your Study Problems</p>
    </div>
  </div>
{% endblock %}

FindTutors/templates/FindTutors/myprofile.html
{% extends 'FindTutors/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto py-5">
      <img class="rounded-circle img-thumbnail mb-5 profile-image" src="{{ user.profile.image.url }}">
      <h2 class="h2 text-center">{{ user.profile.year }}</h2>
      <p class="h3 text-center text-secondary">{{ user.username }}</p>
      <div class="col-md-auto text-center">
        <form action="{% url 'FindTutors:edit_profile' %}">
          <input class="btn btn-warning" type="submit" value="Edit" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

FindTutors/templates/FindTutors/ratings_review.html
{% extends 'FindTutors/base.html' %}
{% block content %}
<form method='POST'>
    {% csrf_token %}{{ form.as_p }}
    <button type='Submit'> Submit Review! </button>
</form>
{% endblock %}

FindTutors/templates/FindTutors/request.html
{% extends 'FindTutors/base.html' %}
{% block content %}
<h2> Request </h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'> Send Request </button>
</form>
{% endblock %}

FindTutors/templates/FindTutors/room_detail.html
{% extends 'FindTutors/base.html' %}
{% block content %}
<h2 class="title">{{room.name}}</h2>
<p class="subtitle">
  {{room.description}}
</p>
{% endblock %}

FindTutors/templates/FindTutors/tutee_signup.html
{% extends 'FindTutors/base.html' %}
{% block content %}
<h2> Create a New Tutee Account </h2>
<form method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit"> Register as Tutee! </button>
</form>
<br>
{% endblock %}

FindTutors/templates/FindTutors/tutees.html
{% extends 'FindTutors/base.html' %}
{% block content %}
<h2>Tutees</h2>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Tutee's Name</th>
      <th>Tutee's Year</th>
      <th>Tutee's Subjects</th>
      <th>Request</th>
    </tr>
  </thead>
  <tbody>
    {% for tutee in tutees %}
    <tr>
      <td><a href="{{tutee.firstname}}/">{{ tutee.firstname }} {{tutee.lastname }}</a></td>
      <td>{{ tutee.year }} </td>
      <td>{{ tutee.subjects }} </td>
      <td><a class="btn btn-primary" href="/../home/request/?recipient={{tutor}}" role="button">Send Request</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

FindTutors/templates/FindTutors/tutor_profile.html
{% extends 'FindTutors/base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto py-5">
      <h1 class="display-4">{{profile.firstname}} {{ profile.lastname }} 's Profile</h1>
      <div class="container-fluid bg-1 text-center py-4">
        {% if profile.image %}
        <img src="{{ profile.image.url }}" width="240">
        {% endif %}
      </div>

      <div class="container-fluid bg-2 text-center">
        <h3> Email </h3>
        <p>{{profile.email }}</p>
      </div>

      <div class="container-fluid bg-3 text-center">
        <h3>Phone Number </h3>
        <p>{{profile.phone_number}}</p>
      </div>

      <div class="container-fluid bg-3 text-center">
        <h3>Subjects </h3>
        <p>{{profile.subjects}}</p>
      </div>
      <div class="container-fluid bg-3 text-center">
        <h3>Years Of Experience </h3>
        <p>{{profile.year}}</p>
      </div>

      <div class="container-fluid bg-3 text-left">
        <h2>Reviews</h2>
        <h5>About {{ profile.firstname }} {{ profile.lastname }}</h5>
        <p>{{profile.bio}}</p>
        {% for review in reviews %}
        <p>{{review.reviews}}</p>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

FindTutors/templates/FindTutors/tutor_registration.html
{% extends 'FindTutors/base.html' %}
{% block content %}
<p>Tutor Registration</p>
<a class="btn-tutor_register btn" href="{% url 'tutor_signup' pk=pk.tutor%}"></a>
{% endblock %}

FindTutors/templates/FindTutors/tutor_signup.html
{% extends 'FindTutors/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-auto py-5">
            <h2>Create a New Tutor Account</h2>
            <div class="form-group">
                <form method="POST" class="post-form" enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{ form.firstname|as_crispy_field }}
                    {{ form.lastname|as_crispy_field }}
                    {{ form.email|as_crispy_field }}
                    {{ form.phone_number|as_crispy_field }}
                    {{ form.subjects|as_crispy_field }}
                    <button type="submit">Register as a Tutor</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

FindTutors/templates/FindTutors/tutors.html
{% extends 'FindTutors/base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-12 py-5">
      <h2>Tutors</h2>
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>Tutor's Name</th>
            <th>Tutor's Year</th>
            <th>Tutor's Subjects</th>
            <th>Request</th>
          </tr>
        </thead>
        <tbody>
          {% for tutor in tutors %}
          <tr>
            <td><a href="{{tutor.id}}/">{{ tutor.firstname }} {{tutor.lastname }}</a></td>
            <td>{{ tutor.year }} </td>
            <td>{{ tutor.subjects }} </td>
            <td><a class="btn btn-warning" href="/../home/request/?recipient={{tutor.email}}" role="button">Send
                Request</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}